BEGIN
	OUTPUT BLANK;

	OUTPUT TAB; OUTPUT BLACK; OUTPUT "Black"; OUTPUT NEWLINE;
	OUTPUT TAB; OUTPUT WHITE; OUTPUT "White"; OUTPUT NEWLINE;
	OUTPUT TAB; OUTPUT GREEN; OUTPUT "Green"; OUTPUT NEWLINE;
	OUTPUT TAB; OUTPUT BLUE; OUTPUT "Blue"; OUTPUT NEWLINE;
	OUTPUT TAB; OUTPUT RED; OUTPUT "Red"; OUTPUT NEWLINE;
	OUTPUT TAB; OUTPUT MAGENTA; OUTPUT "Magenta"; OUTPUT NEWLINE;
	OUTPUT TAB; OUTPUT CYAN; OUTPUT "Cyan"; OUTPUT NEWLINE;
	OUTPUT TAB; OUTPUT YELLOW; OUTPUT "Yellow"; OUTPUT NEWLINE;

	OUTPUT CLEAR;
END
