BEGIN
	OUTPUT BLACK;
	OUTPUT "Black\n";
	OUTPUT WHITE;
	OUTPUT "White\n"
	OUTPUT GREEN;
	OUTPUT "Green\n";
	OUTPUT BLUE;
	OUTPUT "Blue\n";
	OUTPUT RED;
	OUTPUT "Red\n"
	OUTPUT MAGENTA;
	OUTPUT "Magenta\n";
	OUTPUT CYAN;
	OUTPUT "Cyan\n";
	OUTPUT YELLOW;
	OUTPUT "Yellow\n";
	OUTPUT CLEAR;
END
