BEGIN
	DENOTED A;
	DENOTED B;
	A := "4?4";
	B := "0?0";
	IF A ~ B THEN OUTPUT " HOMO TRUE";
	IF A ? B THEN OUTPUT " ISO TRUE";
	OUTPUT NEWLINE;
	A := "4?3";
	B := "0?0";
	IF A ~ B THEN OUTPUT " HOMO TRUE";
	IF A ? B THEN OUTPUT " ISO TRUE";
	OUTPUT NEWLINE;
END
