BEGIN
        DENOTED TITLE;
	TITLE := "TEST 3 : Words";
        OUTPUT TITLE;
	OUTPUT NEWLINE
	DENOTED A;
	DENOTED QUIT;
	QUIT := "blank";

LOOP:	INPUT A;    
        OUTPUT A;
	OUTPUT TAB;
	YIELD;
	IF A ? QUIT THEN GOTO FINIS;
	A := " ";
	GOTO LOOP;

FINIS:  OUTPUT "\n"
END