BEGIN
	INTEGER RND;
	INTEGER ACCUMULATOR;
	INTEGER APPLY;

S1:	RND := RANDOM;
	IF RND < 1 THEN RND := 0; 
	RND := RND % 9;
	IF RND < 1 THEN RND := 0;
	IF ACCUMULATOR = 200 THEN YIELD; GOTO S2;
	IF ACCUMULATOR = 210 THEN YIELD; GOTO S3;
	IF RND = 2 THEN ACCUMULATOR := 200;
	YIELD;
	GOTO S1;

S2:	IF RND = 1 THEN ACCUMULATOR := 210;
	YIELD;
	GOTO S1;

S3:	IF RND = 5 THEN ACCUMULATOR := 215;
	IF ACCUMULATOR != 215 THEN GOTO S2;
	APPLY := 0;
	YIELD;
	APPLY := 53;
	YIELD;
	APPLY :=0;
	YIELD;
	GOTO S1
END